### ISSUE TITLE
Authorization failed. These requirements were not met

### ISSUE THREAD

**Issue by rhollamby** [microsoftgraph/msgraph-training-blazor-clientside#8]
Downloaded completed code and followed instructions from 
https://github.com/microsoftgraph/msgraph-training-blazor-clientside/tree/main/demo

Get the following error when trying to login with AAD Account
`Adding User.Read to requested permissions
Adding MailboxSettings.Read to requested permissions
Adding Calendars.ReadWrite to requested permissions
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.`

**Comment by jasonjoh** [comment]
Apologies for the confusion - the app registration instructions in that README are outdated, which is causing your problem. Specifically, the app should be registered as a SPA, not a web app. Instructions [here](https://docs.microsoft.com/graph/tutorials/blazor?tutorial-step=2) are correct.

**Comment by jasonjoh** [comment]
@rhollamby were you able to try the updated app registration?
